services:
  api:
    profiles: [ "api" ]
    container_name: article_analyzer.api
    build:
      context: .
    expose:
      - "8080"
    ports:
      - "8080:8080"
    networks:
      - article_analyzer.network
    volumes:
      - ./src/article_analyzer:/usr/article_analyzer/src/article_analyzer
    env_file:
      - .env
    command: python -m src.article_analyzer
    healthcheck:
      test: ["CMD-SHELL", "curl -fsSL http://${SERVER_HEALTHCHECK_HOST}:${SERVER_PORT}/api/v1/healthcheck"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s

networks:
  article_analyzer.network:
    name: article_analyzer.network
    driver: bridge
